const { Client } = require('pg');

const connectionString = "postgres://postgres.cjnlbefawsnyqscqvkib:Jfo90mKWeXkYbASW@aws-1-us-east-1.pooler.supabase.com:5432/postgres";

const client = new Client({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
});

async function createTable() {
  try {
    await client.connect();
    console.log("Connected to Supabase Postgres.");

    const createTableQuery = `
      CREATE TABLE IF NOT EXISTS cashier_accounts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        branch TEXT NOT NULL,
        role TEXT NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `;

    await client.query(createTableQuery);
    console.log("Table 'cashier_accounts' created successfully (or already exists).");

  } catch (error) {
    console.error("Error creating table:", error);
  } finally {
    await client.end();
    console.log("Connection closed.");
  }
}

createTable();
