export const columns = [
   {name: 'NAMA KARYAWAN', uid: 'name'},
   {name: 'JABATAN', uid: 'role'},
   {name: 'CABANG', uid: 'team'},
   {name: 'STATUS', uid: 'status'},
   {name: 'ACTIONS', uid: 'actions'},
];
export const users = [
   {
      id: 1,
      name: 'Ahmad Fauzan',
      role: 'Store Manager',
      team: 'Sultan Alauddin',
      status: 'active',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'fauzan@kotacoffee.id',
   },
   {
      id: 2,
      name: 'Rina Wijaya',
      role: 'Head Barista',
      team: 'Perintis',
      status: 'active',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'rina@kotacoffee.id',
   },
   {
      id: 3,
      name: 'Budi Santoso',
      role: 'Kasir Utama',
      team: 'Antang',
      status: 'active',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'budi@kotacoffee.id',
   },
   {
      id: 4,
      name: 'Siti Aminah',
      role: 'Waitress',
      team: 'Sultan Alauddin',
      status: 'vacation',
      age: '28',
      avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
      email: 'siti@kotacoffee.id',
   },
   {
      id: 5,
      name: 'Reza Pahlevi',
      role: 'Barista',
      team: 'BTP',
      status: 'active',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'reza@kotacoffee.id',
   },
   {
      id: 6,
      name: 'Toni Pratama',
      role: 'Supervisor',
      team: 'Pusat',
      status: 'active',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'toni@kotacoffee.id',
   }
];
